#!/bin/bash
docker exec -i symfony-web-v2 bash -c "mkdir -p /var/www/src/Service /var/www/src/Controller /var/www/templates/pdf /var/www/tests/Service"

docker exec -i symfony-web-v2 bash -c "cat > /var/www/src/Service/GotenbergService.php" <<'PHP_SCRIPT_EOF'
<?php

namespace App\Service;

use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\Mime\Part\Multipart\FormDataPart;
use Symfony\Component\Mime\Part\DataPart;

class GotenbergService
{
    public function __construct(
        private HttpClientInterface $client,
        private string $gotenbergUrl,
    ) {
    }

    public function generatePdfFromHtml(string $html): string
    {
        $formFields = [
            'index.html' => DataPart::fromString($html, 'index.html', 'text/html'),
        ];

        $formData = new FormDataPart($formFields);

        $response = $this->client->request(
            'POST',
            $this->gotenbergUrl . '/forms/chromium/convert/html',
            [
                'headers' => $formData->getPreparedHeaders()->toArray(),
                'body' => $formData->bodyToIterable(),
            ]
        );

        return $response->getContent();
    }
}
PHP_SCRIPT_EOF

docker exec -i symfony-web-v2 bash -c "cat > /var/www/src/Controller/PdfController.php" <<'PHP_SCRIPT_EOF'
<?php

namespace App\Controller;

use App\Service\GotenbergService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_USER')]
class PdfController extends AbstractController
{
    #[Route('/pdf/generate', name: 'app_pdf_generate')]
    public function generate(GotenbergService $gotenbergService): Response
    {
        $html = $this->renderView('pdf/template.html.twig', [
            'title' => 'My PDF',
            'content' => 'This is a test PDF generated by Gotenberg.',
        ]);

        $pdfContent = $gotenbergService->generatePdfFromHtml($html);

        return new Response($pdfContent, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="document.pdf"',
        ]);
    }
}
PHP_SCRIPT_EOF

docker exec -i symfony-web-v2 bash -c "cat > /var/www/templates/pdf/template.html.twig" <<'TWIG_EOF'
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <h1>{{ title }}</h1>
    <p>{{ content }}</p>
</body>
</html>
TWIG_EOF

docker exec -i symfony-web-v2 bash -c "cat > /var/www/tests/Service/GotenbergServiceTest.php" <<'PHP_SCRIPT_EOF'
<?php

namespace App\Tests\Service;

use App\Service\GotenbergService;
use PHPUnit\Framework\TestCase;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Contracts\HttpClient\ResponseInterface;

class GotenbergServiceTest extends TestCase
{
    public function testGeneratePdf()
    {
        $response = $this->createMock(ResponseInterface::class);
        $response->expects($this->once())
            ->method('getContent')
            ->willReturn('PDF_CONTENT');

        $client = $this->createMock(HttpClientInterface::class);
        // We expect a POST request. Validating exact arguments for multipart is complex in mock,
        // so we focus on ensuring request is called and returns expected content.
        $client->expects($this->once())
            ->method('request')
            ->willReturn($response);

        $service = new GotenbergService($client, 'http://gotenberg:3000');
        $pdf = $service->generatePdfFromHtml('<html></html>');

        $this->assertEquals('PDF_CONTENT', $pdf);
    }
}
PHP_SCRIPT_EOF
