<?php

namespace App\Controller;

use App\Service\GotenbergService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_USER')]
class PdfController extends AbstractController
{
    #[Route('/pdf/generate', name: 'app_pdf_generate')]
    public function generate(GotenbergService $gotenbergService): Response
    {
        $html = $this->renderView('pdf/template.html.twig', [
            'title' => 'My PDF',
            'content' => 'This is a test PDF generated by Gotenberg.',
        ]);

        $pdfContent = $gotenbergService->generatePdfFromHtml($html);

        return new Response($pdfContent, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => 'inline; filename="document.pdf"',
        ]);
    }
}
